; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppName=ORBI
<<<<<<< HEAD
AppVersion=2.00.69
=======
AppVersion=2.00.68
>>>>>>> ea249b0eb181edecb8a4b97e553e293fa1d1b47d
AppPublisher=TOMASI SISTEMAS DE INFORMAÇÃO
DefaultDirName=C:\ORBI
DefaultGroupName=ORBI
DisableProgramGroupPage=yes
OutputDir=C:\Tomasi Sistemas
OutputBaseFilename=OrbiUpdate
Compression=lzma
SolidCompression=yes
WizardStyle=modern
CloseApplications=yes
CloseApplicationsFilter=Orbi.exe
RestartApplications=no

[Languages]
Name: "brazilianportuguese"; MessagesFile: "compiler:Languages\BrazilianPortuguese.isl"

[Files]
Source: "C:\Tomasi Sistemas\orbi\Orbi.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Tomasi Sistemas\orbi\BorlndMM.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Tomasi Sistemas\orbi\CnpjDll.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Tomasi Sistemas\orbi\DelZip179.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Tomasi Sistemas\orbi\DelZip190.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Tomasi Sistemas\orbi\DelZip192.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Tomasi Sistemas\orbi\DenomoRuntime.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Tomasi Sistemas\orbi\FastMM_FullDebugMode.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Tomasi Sistemas\orbi\iconv.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Tomasi Sistemas\orbi\intl.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Tomasi Sistemas\orbi\libeay32.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Tomasi Sistemas\orbi\libiconv-2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Tomasi Sistemas\orbi\libintl-8.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Tomasi Sistemas\orbi\libpq.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Tomasi Sistemas\orbi\libxml2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Tomasi Sistemas\orbi\libxmlsec.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Tomasi Sistemas\orbi\libxmlsec-openssl.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Tomasi Sistemas\orbi\libxslt.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Tomasi Sistemas\orbi\midas.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Tomasi Sistemas\orbi\msvbvm50.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Tomasi Sistemas\orbi\msvcr120.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Tomasi Sistemas\orbi\NFE_dll.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Tomasi Sistemas\orbi\ssleay32.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Tomasi Sistemas\orbi\UnzDll.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Tomasi Sistemas\orbi\Zip1Dll.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Tomasi Sistemas\orbi\Relatorios\*"; DestDir: "{app}\Relatorios\"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Tomasi Sistemas\orbi\Logos\*"; DestDir: "{app}\Logos\"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Tomasi Sistemas\orbi\Schemas\*"; DestDir: "{app}\Schemas\"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\ORBI"; Filename: "{app}\Orbi.exe"

[Run]
Filename: "{app}\Orbi.exe"; Description: "Abrir o ORBI"; Flags: nowait postinstall skipifsilent
